### ISSUE TITLE
Publishing releases on NuGet.org

### ISSUE THREAD

**Issue by astiskala** [squizzdotcom/ecommerce-standards-documents-dotnet-library#4]
Hi There,

Thanks for the recent fixes and improvements :+1: 

I'm currently building and publishing ESD releases on our internal NuGet server for use in our project. It occurs to me that it may be useful to publish this on the public NuGet.org repository so that it can be more easily accessed.

Before I go ahead and do this, I thought I'd check:
1. That you are okay with me doing this
2. If yes, how I should handle versioning releases in cases where there may not be a release yet on GitHub. For example, there are currently a number of fixes/improvements beyond version 1.00.1. Could I just increment the patch and mark the package as a "pre-release"? In the case of the current master head, it would be 1.00.2-pre1

If you're happy for me to do this, could you please let me know your NuGet username (assuming you have one) so I can add you as an owner?

Thanks,
Adam

**Comment by squizzdev** [comment]
I'm happy to put it up on NuGet, but it might be best to wait until after we have completed implementing it in our own software first before we start spreading it around further.
I'm thinking that it gets released to NuGet after each official release on Git.
I'm also thinking of setting up a separate develop branch in git that contains all committed improvements pre-release.Then its just a case of merging the develop branch to the master when its ready to go.

**Comment by astiskala** [comment]
Sounds good to me. In the interim, I will continue using our private NuGet.

**Comment by astiskala** [comment]
Now that ESD is at v1.1, I'd like to re-open this issue. Could ESD be published on NuGet?

**Comment by squizzdev** [comment]
I've now published it on NuGet at https://www.nuget.org/packages/EcommerceStandardsDocuments.Library/1.1.0 
I'm still new to NuGet so if something's missing or not working let me know.
